config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :featured_image
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: :index
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :author, :featured_image, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <div class='row'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="file">
    <label class="file-label">
      <%= form.file_field :featured_image, class: 'file-input' %>
      <span class="file-cta">
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
        <span class="file-label">
          Escolha a imagem de destaque…
        </span>
      </span>
    </label>
  </div>

  </br>

  <div class="field">
    <%= form.label 'Título', class: 'label' %>
    <div class="control">
      <%= form.text_field :title, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label 'Autor', class: 'label' %>
    <div class="control">
      <%= form.text_field :author, class: 'input' %>
    </div>
  </div>


  <div class="field">
    <%= form.label 'Conteúdo', class: 'label' %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= form.submit 'Criar', class: 'button is-link' %>
    </div>
    <div class="control">
      <%= link_to 'Voltar', posts_path, class: 'button is-link is-light' %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
</br></br>
<h1 class="title">Publicações</h1>
</br>

<% @posts.each do |post| %>
  <div class="columns">
    <div class="column is-four-fifths">
      <div class="card">
        <div class="card-image">
          <figure class="image is-full is-marginless is-3by1">
            <%= image_tag post.featured_image %>
          </figure>
        </div>
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <a href="<%= post_path(id: post.id) %>"><p class="title is-4"><%= post.author %></p></a>
            </div>
          </div>
          <p>Autor: <%= post.author %> - <%= post.created_at.strftime("%d/%m/%Y") %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
</br></br> <h1 class="title is-1">Nova Publicação</h1> 

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
</br></br>
<figure class="image is-3by1">
  <%= image_tag @post.featured_image %>
</figure></br>
<div class="columns">
  <div class="column">
    <p class="title"><%= @post.title %></p>
  </div>
</div></br></br>
<div class="columns">
  <div class="column is-three-quarters"><%= @post.content %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <img src="https://onebitcode.com/wp-content/uploads/2020/01/logo-bg-escuro-400.png" width="auto" height='auto'>
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href='/posts/new'>
          + Nova Publicação
        </a>
      </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% unless user_signed_in? %>
              <a class="button is-primary" href='/users/sign_up'>
                <strong>Cadastre-se</strong>
              </a>
              <a class="button is-light" href='/users/sign_in'>
                Entrar
              </a>
            <% end %>  
            <% if user_signed_in? %>
              <%= link_to "Sair", destroy_user_session_path, method: :delete, class: 'button is-light'  %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>